server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
    use-relative-redirects: true

spring :
  #时间戳统一转换
  jackson:
    time-zone: GMT+8
  dubbo:
    # ApplicationConfig Bean
    application:
      #应用名
      id: websocket-provider
      name: websocket-provider
    # Base packages to scan Dubbo Components (e.g., @Service, @Reference)
    scan:
      #扫描的包名
      base-packages: com.callenled.websocket.service.impl
    # ProtocolConfig Bean
    protocol:
      id: dubbo
      name: dubbo
      #dubbo服务暴露的端口
      port: 20880
    registry:
      #zookeeper地址
      address: localhost
      #提供注册的端口
      port: 2181
